version: '3'
services:
  backend:
    build: ./backend
    command: bash -c "bundle exec rails db:create db:migrate && bundle exec rails server -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env.docker.backend
  sidekiq:
    build: ./backend
    command: bundle exec sidekiq
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env.docker.backend
  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:3000
        REACT_APP_CABLE_ENDPOINT: ws://localhost:3000/cable
        REACT_APP_TOKEN_KEY: token
    ports:
      - "3001:80"
    volumes:
      - ./frontend:/app
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=password
  redis:
    image: redis:6.2
