# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.3.0'

gem 'rails', '~> 7.1.3'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '>= 6.0'
gem 'bcrypt', '~> 3.1.7'

gem 'jwt'
gem 'blueprinter'
gem 'kaminari'
gem 'config'
gem 'oj'
gem 'active_storage_validations'
gem 'bootsnap', require: false
gem 'sidekiq'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

group :development, :test do
  gem 'pry', '~> 0.14.2'
  gem 'pry-byebug'
  gem 'factory_bot_rails'
  gem 'rspec-rails', '~> 5.0', '>= 5.0.2'
  gem 'dotenv'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'rubocop-rspec_rails', require: false
  gem 'rubocop-factory_bot', require: false
  gem 'annotate'
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
